/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Approval
         * @description Record a reviewer's decision. This is the only route that produces a canonical fact.
         *     An identical repeat returns the existing approval with 200 and writes nothing. When
         *     the request names `previous_approval_id` (null: the field was undecided) and the field
         *     has been decided again since, the write is refused with 409. With a review token, only
         *     candidates of the token's tender can be decided.
         */
        post: operations["post_approval_api_v1_approvals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/canonical": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Canonical
         * @description Current canonical facts of an object: approved by a human, with their evidence.
         */
        get: operations["get_canonical_api_v1_canonical_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Document
         * @description Upload a PDF. The same file uploaded twice returns the first document with 200.
         */
        post: operations["upload_document_api_v1_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Extraction
         * @description Queue an extraction run. The worker runs it; poll GET /extraction-runs/{id}.
         */
        post: operations["start_extraction_api_v1_documents__document_id__extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pages
         * @description Every page with its size, so a viewer can lay the document out before any page is
         *     drawn, and where its image is served.
         */
        get: operations["get_pages_api_v1_documents__document_id__pages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/pages/{page_no}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Page Render
         * @description The page as a PNG at the configured render resolution.
         */
        get: operations["get_page_render_api_v1_documents__document_id__pages__page_no__render_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Document
         * @description Where the text occurs in the document, ignoring case: page, box and the words
         *     around it. At most 200 places.
         */
        get: operations["search_document_api_v1_documents__document_id__search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sections */
        get: operations["get_sections_api_v1_documents__document_id__sections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/extraction-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Extraction Run */
        get: operations["get_extraction_run_api_v1_extraction_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files-auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Authorise File
         * @description Asked by the proxy before it serves a stored file (a PDF or a page image): the file
         *     must belong to a document of the review token's tender.
         */
        get: operations["authorise_file_api_v1_files_auth_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Healthy means the database answers and the configured tenant row exists.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/extraction-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Extraction Summary
         * @description What extraction returned for every tender, before review: evidence-location rate,
         *     answer rate, validation failures, tokens and cost, as data and as the Markdown report.
         */
        get: operations["get_extraction_summary_api_v1_reports_extraction_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/review-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Review Session
         * @description Who the review token is and which tender it opens.
         */
        get: operations["get_review_session_api_v1_review_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/review-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Review State
         * @description Every field of the object with its best candidate, evidence, validation and approval.
         */
        get: operations["get_review_state_api_v1_review_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/review-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Review Token
         * @description A review link for one tender and one reviewer, valid for 30 days. An earlier link
         *     for the tender stops working. Not reachable with a review token or from outside.
         */
        post: operations["create_review_token_api_v1_review_tokens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schemas/tender/{tender_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Schema
         * @description The compiled field list of a tender type, in review order.
         */
        get: operations["get_schema_api_v1_schemas_tender__tender_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tenders */
        get: operations["list_tenders_api_v1_tenders_get"];
        put?: never;
        /**
         * Create Tender
         * @description Create a tender. Its documents are added as versions.
         */
        post: operations["create_tender_api_v1_tenders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders/{tender_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tender */
        get: operations["get_tender_api_v1_tenders__tender_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders/{tender_id}/complete-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Review
         * @description Complete the review of the token's tender: refused while a required field has no
         *     decision. Marks the token completed and the tender reviewed, and stores the current
         *     view as the snapshot the gold set is made from.
         */
        post: operations["complete_review_api_v1_tenders__tender_id__complete_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders/{tender_id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Extraction
         * @description Queue the extraction of one version (the latest by default): one run per document.
         *     A version after the original is read only for the sections its documents touch. A long
         *     amendment, or one whose text matches no section keyword, is first mapped in full by a
         *     background job, which then queues its run; such a run is not in this response.
         *     `mode` "batch" sends the calls through the batch API for a run nobody waits for.
         */
        post: operations["start_extraction_api_v1_tenders__tender_id__extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders/{tender_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tender Review
         * @description The tender as the reviewer sees it: every field once, with what each version says
         *     about it and the entry to decide (the latest version that states the field).
         */
        get: operations["get_tender_review_api_v1_tenders__tender_id__review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders/{tender_id}/review-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Review State
         * @description Core's review state for one version of the tender (the latest extracted by default).
         */
        get: operations["get_review_state_api_v1_tenders__tender_id__review_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders/{tender_id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Snapshot
         * @description The final values of the tender's latest completed review.
         */
        get: operations["get_snapshot_api_v1_tenders__tender_id__snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders/{tender_id}/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Summarize
         * @description Queue the summary of the tender, written from its extracted record: each sentence
         *     carries the evidence of the fields it draws on. The worker queues it by itself when
         *     the extraction of a tender ends; this asks for it again (after a field was edited).
         */
        post: operations["summarize_api_v1_tenders__tender_id__summarize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders/{tender_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["list_versions_api_v1_tenders__tender_id__versions_get"];
        put?: never;
        /**
         * Add Version
         * @description Upload a document as a new version of the tender: the original first, then one
         *     version per corrigendum, amendment or clarification; `kind` is required. With
         *     `version_no`, the document is added to that existing version instead (a PPA or a
         *     technical volume): `role` is required and `kind`, if sent, must be that version's own
         *     kind, so a change to the tender can never be filed inside an existing version. The
         *     document is parsed in the background; start extraction once it is.
         */
        post: operations["add_version_api_v1_tenders__tender_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders/{tender_id}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get View
         * @description The current view: per field, the canonical value from the latest version that set
         *     it, with that version's number and kind. Canonical facts only, never candidates.
         */
        get: operations["get_view_api_v1_tenders__tender_id__view_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovalOut */
        ApprovalOut: {
            /** Candidate Id */
            candidate_id: string;
            /** Canonical Fact Id */
            canonical_fact_id: string | null;
            /** Created */
            created: boolean;
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
            /** Decision */
            decision: string;
            /** Feedback Delta Kind */
            feedback_delta_kind: string | null;
            /** Field Path */
            field_path: string;
            /** Final Value */
            final_value: unknown;
            /** Id */
            id: string;
            /** Note */
            note: string | null;
            /** Reviewer */
            reviewer: string;
            /** Status */
            status: string;
        };
        /** ApprovalRequest */
        ApprovalRequest: {
            /** Candidate Id */
            candidate_id: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "edited" | "not_in_document" | "rejected" | "flagged";
            /** Evidence */
            evidence?: components["schemas"]["ReviewerEvidence"][] | null;
            /** Final Value */
            final_value?: unknown;
            /** Note */
            note?: string | null;
            /** Previous Approval Id */
            previous_approval_id?: string | null;
        };
        /** ApprovalView */
        ApprovalView: {
            /** Candidate Id */
            candidate_id: string;
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
            /** Decision */
            decision: string;
            /** Final Value */
            final_value: unknown;
            /** Id */
            id: string;
            /** Note */
            note: string | null;
            /** Reviewer */
            reviewer: string;
        };
        /** Body_add_version_api_v1_tenders__tender_id__versions_post */
        Body_add_version_api_v1_tenders__tender_id__versions_post: {
            /** File */
            file: string;
            /** Issued On */
            issued_on?: string | null;
            /** Kind */
            kind?: string | null;
            /** Role */
            role?: string | null;
            /** Summary Of Change */
            summary_of_change?: string | null;
            /** Version No */
            version_no?: number | null;
        };
        /** Body_upload_document_api_v1_documents_post */
        Body_upload_document_api_v1_documents_post: {
            /** File */
            file: string;
        };
        /** CandidateView */
        CandidateView: {
            /** Confidence */
            confidence: number;
            /** Document Id */
            document_id: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceView"][];
            /** Id */
            id: string;
            /** Prompt Name */
            prompt_name: string;
            /** Prompt Version */
            prompt_version: string;
            /** Rationale */
            rationale: string;
            /** Status */
            status: string;
            /** Validation */
            validation: components["schemas"]["ValidationView"][];
            /** Value */
            value: unknown;
        };
        /** CanonicalFactView */
        CanonicalFactView: {
            /** Approval Id */
            approval_id: string;
            /** Created By */
            created_by: string;
            /**
             * Effective At
             * Format: date-time
             */
            effective_at: string;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            }[];
            /** Field Path */
            field_path: string;
            /** Id */
            id: string;
            /** Object Id */
            object_id: string;
            /** Object Type */
            object_type: string;
            /** Object Version */
            object_version: number;
            /** Value */
            value: unknown;
            /** Value Type */
            value_type: string;
        };
        /** CompiledSection */
        CompiledSection: {
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** Order */
            order: number;
            /** Prompt */
            prompt: string;
            /** Prompt Version */
            prompt_version?: string | null;
            /** Roles */
            roles: string[];
        };
        /** DocumentOut */
        DocumentOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Error */
            error: string | null;
            /** File Url */
            file_url: string;
            /** Filename */
            filename: string;
            /** Id */
            id: string;
            /** Mime */
            mime: string;
            /** Page Count */
            page_count: number | null;
            /** Sha256 */
            sha256: string;
            /** Status */
            status: string;
        };
        /** EvidenceView */
        EvidenceView: {
            /** Bbox */
            bbox: number[] | null;
            /** Char End */
            char_end: number | null;
            /** Char Start */
            char_start: number | null;
            /** Document Id */
            document_id: string;
            /** Id */
            id: string;
            /** Match Method */
            match_method: string | null;
            /** Match Score */
            match_score: number | null;
            /** Ordinal */
            ordinal?: number | null;
            /** Page No */
            page_no: number;
            /** Quote */
            quote: string;
            /** Resolution */
            resolution: string;
            /** Source */
            source?: string | null;
        };
        /** ExtractRequest */
        ExtractRequest: {
            /** Prompt Version */
            prompt_version: string;
            /** Schema Name */
            schema_name: string;
            /** Schema Version */
            schema_version: string;
        };
        /** ExtractionRunOut */
        ExtractionRunOut: {
            /** Cost Usd */
            cost_usd: string;
            /** Document Id */
            document_id: string;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: string;
            /** Mode */
            mode: string;
            /** Model */
            model: string;
            /** Object Id */
            object_id: string;
            /** Object Type */
            object_type: string;
            /** Object Version */
            object_version: number;
            /** Prompt Version */
            prompt_version: string;
            /** Schema Name */
            schema_name: string;
            /** Schema Version */
            schema_version: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
            /** Token Cached */
            token_cached: number;
            /** Token In */
            token_in: number;
            /** Token Out */
            token_out: number;
        };
        /**
         * ExtractionSummary
         * @description The extraction summary as data, and the same content as the Markdown report.
         */
        ExtractionSummary: {
            /** Calls */
            calls: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Markdown */
            markdown: string;
            /** Model */
            model: string;
            /** Tenders */
            tenders: components["schemas"]["TenderSummary"][];
            /** Total Cost Usd */
            total_cost_usd: number;
        };
        /** FieldState */
        FieldState: {
            /** Alternative Candidates */
            alternative_candidates: number;
            approval: components["schemas"]["ApprovalView"] | null;
            candidate: components["schemas"]["CandidateView"] | null;
            /** Enum Values */
            enum_values: string[] | null;
            /** Field Path */
            field_path: string;
            /** Group */
            group: string;
            /** Help Text */
            help_text: string;
            /** Label */
            label: string;
            /** Required */
            required: boolean;
            /** Review Order */
            review_order: number;
            /** Unit */
            unit: string | null;
            /** Value Type */
            value_type: string;
        };
        /** FieldView */
        FieldView: {
            /** Approval Id */
            approval_id: string | null;
            /** Canonical Fact Id */
            canonical_fact_id: string | null;
            /** Decided */
            decided: boolean;
            /** Effective At */
            effective_at: string | null;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            }[];
            /** Field Path */
            field_path: string;
            /** Label */
            label: string;
            /** Section */
            section: string;
            /** Unit */
            unit: string | null;
            /** Value */
            value: unknown;
            /** Value Type */
            value_type: string;
            /** Version Kind */
            version_kind: string | null;
            /** Version No */
            version_no: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Database
             * @constant
             */
            database: "ok";
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Tenant Id */
            tenant_id: string;
        };
        /** PageOut */
        PageOut: {
            /** Has Text Layer */
            has_text_layer: boolean;
            /** Height */
            height: number;
            /** Page No */
            page_no: number;
            /** Render Url */
            render_url: string | null;
            /** Width */
            width: number;
        };
        /** ReviewDocument */
        ReviewDocument: {
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Page Count */
            page_count: number | null;
            /** Role */
            role: string;
        };
        /**
         * ReviewEntry
         * @description What one version says about a field: core's field state for that version.
         */
        ReviewEntry: {
            state: components["schemas"]["FieldState"];
            /** Version Kind */
            version_kind: string;
            /** Version No */
            version_no: number;
        };
        /** ReviewField */
        ReviewField: {
            /** Current */
            current: number | null;
            /** Decided */
            decided: boolean;
            /** Entries */
            entries: components["schemas"]["ReviewEntry"][];
            /** Enum Values */
            enum_values: string[] | null;
            /** Field Path */
            field_path: string;
            /** Flagged */
            flagged: boolean;
            /** Help Text */
            help_text: string;
            /** Label */
            label: string;
            /** Required */
            required: boolean;
            /** Review Order */
            review_order: number;
            /** Section */
            section: string;
            /** Unit */
            unit: string | null;
            /** Value Type */
            value_type: string;
        };
        /** ReviewSection */
        ReviewSection: {
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** Order */
            order: number;
        };
        /** ReviewSessionOut */
        ReviewSessionOut: {
            /** Completed At */
            completed_at: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Reviewer Name */
            reviewer_name: string;
            /** Tender Id */
            tender_id: string;
        };
        /** ReviewState */
        ReviewState: {
            /** Decided */
            decided: number;
            /** Fields */
            fields: components["schemas"]["FieldState"][];
            /** Object Id */
            object_id: string;
            /** Object Type */
            object_type: string;
            /** Object Version */
            object_version: number;
            /** Required Undecided */
            required_undecided: number;
            run: components["schemas"]["RunView"] | null;
            /** Runs */
            runs: components["schemas"]["RunView"][];
            /** Total */
            total: number;
        };
        /** ReviewTokenCreate */
        ReviewTokenCreate: {
            /** Reviewer Name */
            reviewer_name: string;
            /** Tender Id */
            tender_id: string;
        };
        /** ReviewTokenOut */
        ReviewTokenOut: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Reviewer Name */
            reviewer_name: string;
            /** Tender Id */
            tender_id: string;
            /** Token */
            token: string;
            /** Url */
            url: string;
        };
        /** ReviewVersion */
        ReviewVersion: {
            /** Documents */
            documents: components["schemas"]["ReviewDocument"][];
            /** Issued On */
            issued_on: string | null;
            /** Kind */
            kind: string;
            /** Version No */
            version_no: number;
        };
        /**
         * ReviewerEvidence
         * @description Evidence the reviewer gives for an edited value: the page and the text on it.
         */
        ReviewerEvidence: {
            /** Page No */
            page_no: number;
            /** Quote */
            quote: string;
        };
        /** RunView */
        RunView: {
            /** Document Id */
            document_id: string;
            /** Groups */
            groups: string[] | null;
            /** Id */
            id: string;
            /** Model */
            model: string;
            /** Prompt Version */
            prompt_version: string;
            /** Schema Name */
            schema_name: string;
            /** Schema Version */
            schema_version: string;
            /** Status */
            status: string;
        };
        /** SearchHit */
        SearchHit: {
            /** Bbox */
            bbox: number[] | null;
            /** Page No */
            page_no: number;
            /** Snippet */
            snippet: string;
        };
        /** SectionOut */
        SectionOut: {
            /** Confidence */
            confidence: number;
            /** End Page */
            end_page: number;
            /** Heading */
            heading: string;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Start Page */
            start_page: number;
        };
        /** SnapshotOut */
        SnapshotOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Reviewer */
            reviewer: string;
            /** Snapshot */
            snapshot: {
                [key: string]: unknown;
            };
            /** Tender Id */
            tender_id: string;
        };
        /** SummaryQueued */
        SummaryQueued: {
            /** Queued */
            queued: boolean;
            /** Tender Id */
            tender_id: string;
        };
        /** TenderCreate */
        TenderCreate: {
            /** Agency */
            agency: string;
            /** External Ref */
            external_ref?: string | null;
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /** TenderExtractRequest */
        TenderExtractRequest: {
            /**
             * Mode
             * @default sync
             * @enum {string}
             */
            mode: "sync" | "batch";
            /**
             * Prompt Version
             * @default v1
             */
            prompt_version: string;
            /** Version No */
            version_no?: number | null;
        };
        /**
         * TenderField
         * @description One compiled field of a tender type, with where it comes from.
         */
        TenderField: {
            /** Domain */
            domain: string | null;
            /** Enum Values */
            enum_values: string[] | null;
            /** Help Text */
            help_text: string;
            /** Item Keys */
            item_keys: string[] | null;
            /** Label */
            label: string;
            /** Namespace */
            namespace: string;
            /** Path */
            path: string;
            /** Required */
            required: boolean;
            /** Review Order */
            review_order: number;
            /** Section */
            section: string;
            /** Subdomain */
            subdomain: string | null;
            /** Unit */
            unit: string | null;
            /** Value Type */
            value_type: string;
        };
        /** TenderOut */
        TenderOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Current Version No */
            current_version_no: number | null;
            /** External Ref */
            external_ref: string | null;
            /** Id */
            id: string;
            /** Issuing Agency */
            issuing_agency: string;
            /** Slug */
            slug: string | null;
            /** Status */
            status: string;
            /** Tender Type */
            tender_type: string;
            /** Title */
            title: string;
        };
        /** TenderReview */
        TenderReview: {
            /** Can Complete */
            can_complete: boolean;
            /** Decided */
            decided: number;
            /** Fields */
            fields: components["schemas"]["ReviewField"][];
            /** Issuing Agency */
            issuing_agency: string;
            /** Required Undecided */
            required_undecided: number;
            /** Sections */
            sections: components["schemas"]["ReviewSection"][];
            /** Status */
            status: string;
            /** Summary */
            summary?: {
                [key: string]: unknown;
            } | null;
            /** Tender Id */
            tender_id: string;
            /** Tender Type */
            tender_type: string;
            /** Title */
            title: string;
            /** Total */
            total: number;
            /** Versions */
            versions: components["schemas"]["ReviewVersion"][];
        };
        /**
         * TenderReviewState
         * @description Core's review state for one version of a tender. For a version after the original,
         *     changed_fields lists the fields that version gives a value for; every other field
         *     keeps what the earlier versions say. A required field is required of the tender, not
         *     of each version: missing_required lists those no version up to this one states.
         */
        TenderReviewState: {
            /** Changed Fields */
            changed_fields?: string[];
            /** Missing Required */
            missing_required?: string[];
            state: components["schemas"]["ReviewState"];
            /** Tender Id */
            tender_id: string;
            /** Version Kind */
            version_kind: string | null;
            /** Version No */
            version_no: number | null;
        };
        /** TenderSchemaOut */
        TenderSchemaOut: {
            /** Fields */
            fields: components["schemas"]["TenderField"][];
            /** Pack */
            pack: string;
            /** Schema Name */
            schema_name: string;
            /** Schema Version */
            schema_version: string;
            /** Sections */
            sections: components["schemas"]["CompiledSection"][];
            /** Tender Type */
            tender_type: string;
        };
        /** TenderSummary */
        TenderSummary: {
            /** Cost Usd */
            cost_usd: string;
            /** Documents */
            documents: number;
            /** Failing Validation */
            failing_validation: number;
            /** Fields */
            fields: number;
            /** Located */
            located: number;
            /** Pages */
            pages: number;
            /** Runs */
            runs: number;
            /** Slug */
            slug: string | null;
            /** Tender Id */
            tender_id: string;
            /** Tender Type */
            tender_type: string;
            /** Title */
            title: string;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Unfinished Runs */
            unfinished_runs: number;
            /** Versions */
            versions: number;
            /** With Value */
            with_value: number;
        };
        /** TenderView */
        TenderView: {
            /** Current Version No */
            current_version_no: number | null;
            /** Decided */
            decided: number;
            /** Fields */
            fields: components["schemas"]["FieldView"][];
            /** Tender Id */
            tender_id: string;
            /** Tender Type */
            tender_type: string;
            /** Total */
            total: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationView */
        ValidationView: {
            /** Message */
            message: string;
            /** Passed */
            passed: boolean;
            /** Rule Name */
            rule_name: string;
            /** Severity */
            severity: string;
        };
        /** VersionDocumentOut */
        VersionDocumentOut: {
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Page Count */
            page_count: number | null;
            /** Role */
            role: string;
            /** Status */
            status: string;
        };
        /** VersionOut */
        VersionOut: {
            /** Documents */
            documents: components["schemas"]["VersionDocumentOut"][];
            /** Id */
            id: string;
            /** Issued On */
            issued_on: string | null;
            /** Kind */
            kind: string;
            /** Summary Of Change */
            summary_of_change: string | null;
            /** Supersedes Version Id */
            supersedes_version_id: string | null;
            /** Tender Id */
            tender_id: string;
            /** Version No */
            version_no: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_approval_api_v1_approvals_post: {
        parameters: {
            query?: never;
            header?: {
                "x-reviewer"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_canonical_api_v1_canonical_get: {
        parameters: {
            query: {
                object_type: string;
                object_id: string;
                version?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanonicalFactView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_v1_documents_post: {
        parameters: {
            query?: never;
            header?: {
                "x-reviewer"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_extraction_api_v1_documents__document_id__extract_post: {
        parameters: {
            query?: never;
            header?: {
                "x-reviewer"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pages_api_v1_documents__document_id__pages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_render_api_v1_documents__document_id__pages__page_no__render_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                page_no: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_document_api_v1_documents__document_id__search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sections_api_v1_documents__document_id__sections_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_extraction_run_api_v1_extraction_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    authorise_file_api_v1_files_auth_get: {
        parameters: {
            query?: never;
            header?: {
                "x-forwarded-uri"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_extraction_summary_api_v1_reports_extraction_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionSummary"];
                };
            };
        };
    };
    get_review_session_api_v1_review_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSessionOut"];
                };
            };
        };
    };
    get_review_state_api_v1_review_state_get: {
        parameters: {
            query: {
                object_type: string;
                object_id: string;
                version?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_review_token_api_v1_review_tokens_post: {
        parameters: {
            query?: never;
            header?: {
                "x-reviewer"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewTokenCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewTokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schema_api_v1_schemas_tender__tender_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tender_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderSchemaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tenders_api_v1_tenders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderOut"][];
                };
            };
        };
    };
    create_tender_api_v1_tenders_post: {
        parameters: {
            query?: never;
            header?: {
                "x-reviewer"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tender_api_v1_tenders__tender_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_review_api_v1_tenders__tender_id__complete_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_extraction_api_v1_tenders__tender_id__extract_post: {
        parameters: {
            query?: never;
            header?: {
                "x-reviewer"?: string | null;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenderExtractRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tender_review_api_v1_tenders__tender_id__review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderReview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_state_api_v1_tenders__tender_id__review_state_get: {
        parameters: {
            query?: {
                version?: number | null;
            };
            header?: never;
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderReviewState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshot_api_v1_tenders__tender_id__snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summarize_api_v1_tenders__tender_id__summarize_post: {
        parameters: {
            query?: never;
            header?: {
                "x-reviewer"?: string | null;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryQueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_v1_tenders__tender_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_version_api_v1_tenders__tender_id__versions_post: {
        parameters: {
            query?: never;
            header?: {
                "x-reviewer"?: string | null;
            };
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_add_version_api_v1_tenders__tender_id__versions_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_view_api_v1_tenders__tender_id__view_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
