"""core: documents, pages, sections, extraction, truth tables, audit log, jobs

Revision ID: 0002
Revises: 0001
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('row_id', sa.String(length=32), nullable=False),
    sa.Column('before', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_row_id'), 'audit_log', ['row_id'], unique=False)
    op.create_index(op.f('ix_audit_log_table_name'), 'audit_log', ['table_name'], unique=False)
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_table('document',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sha256', name='uq_document_tenant_sha256')
    )
    op.create_index(op.f('ix_document_tenant_id'), 'document', ['tenant_id'], unique=False)
    op.create_table('job',
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_status'), 'job', ['status'], unique=False)
    op.create_index(op.f('ix_job_tenant_id'), 'job', ['tenant_id'], unique=False)
    op.create_table('extraction_run',
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('object_id', sa.String(length=32), nullable=False),
    sa.Column('object_version', sa.Integer(), nullable=False),
    sa.Column('schema_name', sa.String(length=100), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_in', sa.Integer(), nullable=False),
    sa.Column('token_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('is_fixture', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_run_document_id'), 'extraction_run', ['document_id'], unique=False)
    op.create_index(op.f('ix_extraction_run_tenant_id'), 'extraction_run', ['tenant_id'], unique=False)
    op.create_table('page',
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('render_path', sa.String(length=500), nullable=False),
    sa.Column('char_boxes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('has_text_layer', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_no', name='uq_page_document_page_no')
    )
    op.create_index(op.f('ix_page_document_id'), 'page', ['document_id'], unique=False)
    op.create_index(op.f('ix_page_tenant_id'), 'page', ['tenant_id'], unique=False)
    op.create_table('section',
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('start_page', sa.Integer(), nullable=False),
    sa.Column('end_page', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=500), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_section_document_id'), 'section', ['document_id'], unique=False)
    op.create_index(op.f('ix_section_tenant_id'), 'section', ['tenant_id'], unique=False)
    op.create_table('candidate',
    sa.Column('extraction_run_id', sa.String(length=32), nullable=False),
    sa.Column('field_path', sa.String(length=200), nullable=False),
    sa.Column('value', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('value_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('prompt_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('llm_call_log_id', sa.String(length=32), nullable=True),
    sa.Column('window_pages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_run.id'], ),
    sa.ForeignKeyConstraint(['llm_call_log_id'], ['llm_call_log.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_extraction_run_id'), 'candidate', ['extraction_run_id'], unique=False)
    op.create_index(op.f('ix_candidate_field_path'), 'candidate', ['field_path'], unique=False)
    op.create_index(op.f('ix_candidate_tenant_id'), 'candidate', ['tenant_id'], unique=False)
    op.create_table('approval',
    sa.Column('candidate_id', sa.String(length=32), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('object_id', sa.String(length=32), nullable=False),
    sa.Column('object_version', sa.Integer(), nullable=False),
    sa.Column('field_path', sa.String(length=200), nullable=False),
    sa.Column('final_value', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reviewer', sa.String(length=200), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('supersedes_approval_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['supersedes_approval_id'], ['approval.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_candidate_id'), 'approval', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_approval_object_id'), 'approval', ['object_id'], unique=False)
    op.create_index(op.f('ix_approval_tenant_id'), 'approval', ['tenant_id'], unique=False)
    op.create_table('evidence_span',
    sa.Column('candidate_id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('stated_page_no', sa.Integer(), nullable=False),
    sa.Column('bbox', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_span_candidate_id'), 'evidence_span', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_evidence_span_tenant_id'), 'evidence_span', ['tenant_id'], unique=False)
    op.create_table('validation_result',
    sa.Column('candidate_id', sa.String(length=32), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_result_candidate_id'), 'validation_result', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_validation_result_tenant_id'), 'validation_result', ['tenant_id'], unique=False)
    op.create_table('canonical_fact',
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('object_id', sa.String(length=32), nullable=False),
    sa.Column('object_version', sa.Integer(), nullable=False),
    sa.Column('field_path', sa.String(length=200), nullable=False),
    sa.Column('value', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('value_type', sa.String(length=50), nullable=False),
    sa.Column('approval_id', sa.String(length=32), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approval.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_fact_object_id'), 'canonical_fact', ['object_id'], unique=False)
    op.create_index(op.f('ix_canonical_fact_tenant_id'), 'canonical_fact', ['tenant_id'], unique=False)
    op.create_table('feedback',
    sa.Column('approval_id', sa.String(length=32), nullable=False),
    sa.Column('field_path', sa.String(length=200), nullable=False),
    sa.Column('candidate_value', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('final_value', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('delta_kind', sa.String(length=20), nullable=False),
    sa.Column('reviewer', sa.String(length=200), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approval.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_approval_id'), 'feedback', ['approval_id'], unique=False)
    op.create_index(op.f('ix_feedback_tenant_id'), 'feedback', ['tenant_id'], unique=False)
    op.add_column('llm_call_log', sa.Column('extraction_run_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_llm_call_log_extraction_run_id'), 'llm_call_log', ['extraction_run_id'], unique=False)
    op.create_foreign_key('llm_call_log_extraction_run_id_fkey', 'llm_call_log', 'extraction_run', ['extraction_run_id'], ['id'])
    # ### end Alembic commands ###

    # Invariants enforced by the database, not only by the service layer.
    op.execute(
        """
        CREATE FUNCTION candidate_immutable() RETURNS trigger AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION 'candidate rows are immutable: delete refused';
            END IF;
            IF (to_jsonb(NEW) - 'status') IS DISTINCT FROM (to_jsonb(OLD) - 'status') THEN
                RAISE EXCEPTION 'candidate rows are immutable: only status may change';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        "CREATE TRIGGER candidate_immutable BEFORE UPDATE OR DELETE ON candidate "
        "FOR EACH ROW EXECUTE FUNCTION candidate_immutable()"
    )
    op.execute(
        """
        CREATE FUNCTION forbid_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION '% rows are append-only: % refused', TG_TABLE_NAME, TG_OP;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    for table in ("evidence_span", "audit_log"):
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION forbid_mutation()"
        )


def downgrade() -> None:
    for table in ("evidence_span", "audit_log"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}")
    op.execute("DROP TRIGGER IF EXISTS candidate_immutable ON candidate")
    op.execute("DROP FUNCTION IF EXISTS forbid_mutation()")
    op.execute("DROP FUNCTION IF EXISTS candidate_immutable()")
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('llm_call_log_extraction_run_id_fkey', 'llm_call_log', type_='foreignkey')
    op.drop_index(op.f('ix_llm_call_log_extraction_run_id'), table_name='llm_call_log')
    op.drop_column('llm_call_log', 'extraction_run_id')
    op.drop_index(op.f('ix_feedback_tenant_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_approval_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_canonical_fact_tenant_id'), table_name='canonical_fact')
    op.drop_index(op.f('ix_canonical_fact_object_id'), table_name='canonical_fact')
    op.drop_table('canonical_fact')
    op.drop_index(op.f('ix_validation_result_tenant_id'), table_name='validation_result')
    op.drop_index(op.f('ix_validation_result_candidate_id'), table_name='validation_result')
    op.drop_table('validation_result')
    op.drop_index(op.f('ix_evidence_span_tenant_id'), table_name='evidence_span')
    op.drop_index(op.f('ix_evidence_span_candidate_id'), table_name='evidence_span')
    op.drop_table('evidence_span')
    op.drop_index(op.f('ix_approval_tenant_id'), table_name='approval')
    op.drop_index(op.f('ix_approval_object_id'), table_name='approval')
    op.drop_index(op.f('ix_approval_candidate_id'), table_name='approval')
    op.drop_table('approval')
    op.drop_index(op.f('ix_candidate_tenant_id'), table_name='candidate')
    op.drop_index(op.f('ix_candidate_field_path'), table_name='candidate')
    op.drop_index(op.f('ix_candidate_extraction_run_id'), table_name='candidate')
    op.drop_table('candidate')
    op.drop_index(op.f('ix_section_tenant_id'), table_name='section')
    op.drop_index(op.f('ix_section_document_id'), table_name='section')
    op.drop_table('section')
    op.drop_index(op.f('ix_page_tenant_id'), table_name='page')
    op.drop_index(op.f('ix_page_document_id'), table_name='page')
    op.drop_table('page')
    op.drop_index(op.f('ix_extraction_run_tenant_id'), table_name='extraction_run')
    op.drop_index(op.f('ix_extraction_run_document_id'), table_name='extraction_run')
    op.drop_table('extraction_run')
    op.drop_index(op.f('ix_job_tenant_id'), table_name='job')
    op.drop_index(op.f('ix_job_status'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_document_tenant_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_table_name'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_row_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
